### ISSUE TITLE
Server side render 

### ISSUE THREAD

**Issue by saeedjalalisj** [cedarstudios/cedarmaps-react-sdk#1]
When using cedarmap on server got this error:
`Dynamic page loading failed ReferenceError: self is not defined`

**Comment by sinaabadi** [comment]
Hi @saeedjalalisj ,
Our SDK is based on mapbox-gl-js and this is client-side module; it doesn't work in node.js (SSR) except in very specialized circumstances. Please see [this link](https://github.com/mapbox/mapbox-gl-js/issues/4593).
