### ISSUE TITLE
can not resolve module path in reactjs project

### ISSUE THREAD

**Issue by ahmadkam72** [cedarstudios/cedarmaps-react-sdk#2]
I read the user guide and add CedarMap component to my reactjs project, but I got this error
"

> reactjs cannot resolve module path

 "

I edited eslint file in my project and error solved, but map did not appear.

I checked network tab in my browser for response of map requests and noticed that
responses are not image file.
I send the request response sample here

Thank you.
[64256-64511.zip](https://github.com/cedarstudios/cedarmaps-react-sdk/files/3565274/64256-64511.zip)

**Comment by mohsentaleb** [comment]
@ahmadkam72 There's only a `.pbf` file in your zip file which is a binary and cannot be read.

**Comment by ahmadkam72** [comment]
That is the response of my requests.
A .pbf file that I can not read.
I know that must get image files from response of this request but I cant.
What is wrong in my way?

My request samples are like this ==> 
https://api.cedarmaps.com/v1/tiles/cedarmaps.light/11/1315/806.pbf?access_token=8d8be29d01ea833ea7bacdd1836567d67c678a70

that have .pbf before access_tocken and responses are .pbf files.

Where this request url created?
Maybe I editing the url can solve my problem.

**Comment by ahmadkam72** [comment]
I followed the steps and get the request url.
The url have a .pbf inside.
Thats a server response and so I can not edit it 
Can you help me to solve this problem?
Thank you.

**Comment by mohsentaleb** [comment]
Vector tiles are encoded in `.pbf` files (Google Protobufs) . Think of it as being like a `.png` image file, but it contains vector map data which then along with vector styles makes up your final map tile. Read about the specification [here](https://docs.mapbox.com/vector-tiles/specification/).

Anyways, the context of the thread here is totally irrelevant to your initial issue, so please describe your problem and let us know how to reproduce it, otherwise we have to close this issue.

**Comment by ahmadkam72** [comment]
Im using DecarMap in my reactjs project.
I added the component as in your tutorial page. but map is not showing in my project.
when I checked network tab of my browser, I noticed that request headers differ from 
legal state (have .pbf instead .png in tile url).
tiles url are server side parameter and I can not change it manually.
Could you help me to solve this? 
OR 
Some information please?

**Comment by mohsentaleb** [comment]
Please check out our basic usage example: https://github.com/cedarstudios/cedarmaps-react-sdk/tree/master/example

**Comment by ahmadkam72** [comment]
My problem solved.
bootstarp styles were affected the map <canvas/> and show the map out of page.
